site_name: P&P PDF Reader
site_description: A modern PDF reader and annotator for iPad
site_url: https://pp-pdf-reader.com/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: white
      accent: red
  font:
    text: SF Pro Display
    code: SF Mono
  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - search.suggest
    - navigation.expand
    - search.highlight

nav:
  - Home: index.md
  - Explore Features: 00-Explore.md
  - Feature Highlights:
      - Home view: 02-Home-view.md
      - Folder view: 03-Folder-view.md
      - Read and annotate PDFs: 01-PDF-view.md
      - Ergonomics: ergonomics.md
      # - PDF touch regions: touch-regions.md
  - Contact Us: contact.md
  # - Support: support.md
  # - Privacy Policy: privacy.md


extra_css:
  - stylesheets/extra.css
  - stylesheets/principles.css
  - stylesheets/contact.css
